name: Build and Deploy FastAPI App

on:
  push:
    branches:
      - main  # Измените на нужную ветку

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4  # Обновлено до v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3  # Обновлено до v3

    - name: Cache Docker layers
      uses: actions/cache@v4  # Обновлено до v4
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Login to DockerHub
      uses: docker/login-action@v3  # Обновлено до v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and push Docker image
      run: |
        docker buildx build --cache-from type=local,src=/tmp/.buildx-cache --cache-to type=local,dest=/tmp/.buildx-cache --push --tag serf1r/hakaton:latest .

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Copy docker-compose.yml to server
      run: scp docker-compose.yml root@77.221.159.69:/path/to/your/app

    - name: Pull and run Docker image on server
      run: |
        ssh root@77.221.159.69 << 'EOF'
          cd /path/to/your/app
          docker-compose pull
          docker-compose up -d
          docker-compose exec -T app alembic upgrade head
        EOF
